---
language: python
python: 
  - "2.7"
  - "3.6"
# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
services:
  - docker
install:
  # Install ansible
  - pip install ansible molecule docker

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../nremote_tmp = /var/tmp/${USER}/ansible' >ansible.cfg


script:
  - molecule --version
  - ansible --version
  - molecule test
  # Basic role syntax check
  # - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/