---
- name: "Check if yamllint is installed"
  package_facts:
    manager: "auto"

- name: Install yamllint
  apk:
    name: yamllint
    state: latest
  when: "'yamllint' not in ansible_facts.packages"

- name: Populate yamllint config
  template:
    src: "{ yamllint_config }}"
    dest: "{{ yamllint_config }}"

- name: Populate yaml file
  template:
    src: "{{ item }}"
    dest: "{{ item }}-{{ env }}"
  with_items:
    - "{{ yaml_files }}"

- name: Validation with yamllint
  shell: "yamllint -c yamllint.yml {{ item }}-{{ env }}"
  register: output
  with_items:
    - "{{ yaml_files }}"