---
- name: Check if yamllint is installed
  package_facts:
    manager: auto

- name: Install yamllint Alpine
  apk:
    name: yamllint
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_os_family == 'Alpine'"

- name: Enable EPEL Repository on CentOS 8
  become: true
  yum:
    name: epel-release
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_facts['os_family'] == 'RedHat'"

- name: Install yamllint on RedHat
  yum:
    name: yamllint
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Populate yamllint config
  template:
    src: "{{templates_folder_yamllint}}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
    mode: u=rwx,g=rwx,o=rx,g+s
  with_items:
    - "{{ yamllint_config }}"

- name: Populate yaml file
  template:
    src: "{{templates_folder_yaml}}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
    mode: u=rwx,g=rwx,o=rx,g+s
  with_items:
    - "{{ yaml_files }}"
  
- name: Validation with yamllint
  shell: "yamllint -c {{ item.0 }}-{{ env }} {{ item.1 }}-{{ env }}"
  register: xmlvallidation
  changed_when: xmlvallidation.rc != 0
  with_together:
    - "{{ yamllint_config }}"
    - "{{ yaml_files }}"

- name: Delete validated files
  file:
    path: "{{ item }}-{{ env }}" #correction code
    state: absent
  with_items:
    - "{{ yamllint_config }}"
    - "{{ yaml_files }}"