---
- name: Check if yamllint is installed
  package_facts:
    manager: auto

- name: Install yamllint Alpine
  apk:
    name: yamllint
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_os_family == 'Alpine'"

- name: Enable EPEL Repository on CentOS 8
  yum:
    name: epel-release
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'"

- name: Install yamllint on RedHat
  yum:
    name: yamllint
    state: latest
  when: "'yamllint' not in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Populate yamllint config
  template:
    src: "{{ yamllint_config }}"
    dest: "{{ yamllint_config }}"

- name: Populate yaml file
  template:
    src: "{{templates_folder}}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
  with_items:
    - "{{ yaml_files }}"

- name: Validation with yamllint
  shell: "yamllint -c yamllint.yml {{ item }}-{{ env }}"
  register: output
  with_items:
    - "{{ yaml_files }}"
