---
- name: Converge
  hosts: localhost
  gather_facts: true
  tasks:
    - name: "Include ansible-role-yaml-validation"
      ansible.builtin.include_role:
        name: "ansible-role-yaml-validation"
