---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: CentOS
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: Alpine
    image: airdata/python-3.9-alpine-bash
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
