---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: alpine:latest
  - name: instance
    image: centos:7
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - verify
